name: Android CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./android-app

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        


    # Save gradle cache between runs, see https://github.com/actions/cache/blob/master/examples.md#java---gradle
    # Include hashFiles so that cache does continue to grow with old dependencies in it.
    - name: Copy gradle cache
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-


    - name: Build with Gradle
      run: ./gradlew build
